sudo: required
services: 
  - docker

# https://docs.travis-ci.com/user/customizing-the-build/
# build only on specific branches
branches:
  only:
    - master
    - main

before_install:
  - docker build -t uditmanav/react-test -f ./client/Dockerfile.dev ./client

script:
  # -- --coverage is used to make npm exit after completing tests
  # - docker run uditmanav/react-test npm test -- --coverage
  - docker run -e CI=true uditmanav/react-test npm run test

after_success:
  - docker build -t uditmanav/multi-client ./client
  - docker build -t uditmanav/multi-nginx ./nginx
  - docker build -t uditmanav/multi-worker ./worker
  - docker build -t uditmanav/multi-server ./server
  # login to dockerhub via docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push uditmanav/multi-client 
  - docker push uditmanav/multi-nginx
  - docker push uditmanav/multi-worker
  - docker push uditmanav/multi-server

# deploy:
#   provider: elasticbeanstalk
#   region: 'us-east-1'
#   app: 'multi-docker'
#   env: 'MultiDocker-env'
#   bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
#   bucket_path: 'docker-multi'
#   on:
#     branch: master
#   # AWS_ACCESS_KEY and AWS_SECRET_KEY needs to be set in travis environment
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY

